include(
    ":app",
    ":feature:oauth",
    ":feature:media",
    ":feature:timeline",
    ":feature:shortcut",
    ":feature:input",
    ":candysh",
    ":data:local-source",
    ":data:restclient",
    ":data:repository",
    ":data:repository-api",
    ":model"
)
include(
    ":test-common",
    ":test-common-jvm"
)
