@startuml

class Activity
class Fragment
class ViewModel {
  viewModelSource: ViewModelSource
  state: LiveData<State>
}

class EventDispatcher
interface EventListener
interface Actions {
  action: Flow<AppEvent>
}
class ConcreteActions {
  dispatcher: EventDispatcher
}
class ViewModelSource {
  actions: ConcreteActions
  stateSource: Flow<State>
}
class NavigationDelegate {
  navController: NavController
}

Activity *- Fragment
Activity -- ViewModel
Activity *- NavigationDelegate

Fragment -- ViewModel
Fragment *- NavigationDelegate

ViewModel *-- ViewModelSource : > delegate

EventListener <|- ViewModel
EventListener <|-- Actions
EventListener <|-- ViewModelSource

Actions <|-- ConcreteActions
ConcreteActions - EventDispatcher

ViewModelSource *- ConcreteActions : > delegate
ViewModelSource - UseCase
ViewModelSource - Repository

UseCase -- Repository
@enduml
