@startuml

class Activity
class Fragment
class ViewModel {
  dispatcher: EventDispatcher
  states: ViewStates
}

class EventDispatcher 
class Actions {
  dispatcher: EventDispatcher
}
class ViewStates {
  actions: Actions
}
class NavigationDelegate {
  navController: NavController
}

Activity *- Fragment
Activity -- ViewModel
Activity o- NavigationDelegate

Fragment -- ViewModel
Fragment o- NavigationDelegate

EventDispatcher - ViewModel
EventDispatcher -- Actions : < observe

ViewModel o-- ViewStates : > observe

ViewStates - Actions : > observe
'ViewStates *-- NavigationDelegate
ViewStates -- Repository
@enduml
