@startuml
entity tweet {
  * id: TweetId [PK]
  * text: String
  * retweet_count: Int
  * favorite_count: Int
  * user_id: UserId
  retweeted_tweet_id: TweetId
  quoted_tweet_id: TweetId
  in_reply_to_tweet_id: TweetId
  * is_retweeted: Boolean
  * is_favorited: Boolean
  * possibly_sensitive: Boolean
  * source: String
  * created_at: Instant
}

entity user_reply {
  * tweet_id: TweetId
  * user_id: UserId
  * screen_name: String
  * start: Int
  * end: Int
}

entity media {
  id: MediaId [PK]
  media_url: String
  url: String
  type: String
  ' fixme @Embedded
    @Embedded(prefix = "large_"}:Size?
    @Embedded(prefix = "medium_"): Size?
    @Embedded(prefix = "small_"): Size?
    @Embedded(prefix = "thumb_"): Size?
  video_aspect_ratio_width: Int?
  video_aspect_ratio_height: Int?
  video_duration_millis: Long?
}

' add MediaItem.Size columns

entity video_valiant {
  media_id: MediaId
  url: String
  bitrate: Int
  content_type: String
}

entity relation_tweet_media {
  tweet_id: TweetId
  media_id: MediaId
}

@enduml
