name: pull request check

on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ hashFiles('**/src/**/*.*', '**/*.gradle', '**/*.kts', 'licences.yml') }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: assemble
        run: ./gradlew assembleDebug

  androidLint:
    name: android lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ hashFiles('**/src/**/*.*', '**/*.gradle', '**/*.kts', 'licences.yml') }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: android lint
        run: ./gradlew lintDebug

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ hashFiles('**/src/**/*.*', '**/*.gradle', '**/*.kts', 'licences.yml') }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: ktlint
        run: ./gradlew ktlintCheck

  unitTest:
    name: unit test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ hashFiles('(**/src/**/*.*', '**/*.gradle', '**/*.kts', 'licences.yml') }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: unit test
        run: ./gradlew testDebugUnitTest

  report:
    runs-on: ubuntu-latest
    needs: [androidLint, ktlint, unitTest]
    steps:
      - uses: actions/checkout@v2
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ hashFiles('(**/src/**/*.*', '**/*.gradle', '**/*.kts', 'licences.yml') }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: Danger
        uses: danger/kotlin@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
