name: lint check

on: pull_request

jobs:
  build:
    name: pull request check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/build.gradle.kts', 'buildSrc/src/main/java/*.kt', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: android lint
        run: ./gradlew lintDebug

      - name: ktlint
        run: ./gradlew ktlintCheck

      - name: unit test
        run: ./gradlew testDebugUnitTest

      - name: Danger
        uses: danger/kotlin@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
