name: lint check

on: [push, pull_request]

jobs:
  build:
    name: lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: android lint
          run: ./gradlew lintDebug
      - name: ktlint
          run: ./gradlew ktlintCheck
      - name: Danger
        uses: danger/kotlin@0.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
