name: pull request check

on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./.gradle
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: check license
        run: ./gradlew :app:checkLicenses
      - name: assemble
        run: ./gradlew compileDebugSources

  androidLint:
    name: android lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./.gradle
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: store lint result
        uses: actions/cache@v2
        with:
          path: ./**/build/reports/lint-results-*.xml
          key: ${{ runner.os }}-result-${{ github.sha }}-lint
      - name: android lint
        run: ./gradlew :app:lint

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./.gradle
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: store ktlint result
        uses: actions/cache@v2
        with:
          path: ./**/build/reports/ktlint
          key: ${{ runner.os }}-result-${{ github.sha }}-ktlint
      - name: ktlint
        run: ./gradlew ktlintCheck

  unitTest:
    name: unit test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./.gradle
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: cache build
        uses: actions/cache@v2
        with:
          path: ./**/build
          key: ${{ runner.os }}-assemble-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-assemble-
      - name: store unit test result
        uses: actions/cache@v2
        with:
          path: ./**/build/test-results
          key: ${{ runner.os }}-result-${{ github.sha }}-unittest
      - name: unit test
        run: ./gradlew testDebugUnitTest

  report:
    runs-on: ubuntu-latest
    needs: [ androidLint, ktlint, unitTest ]
    steps:
      - uses: actions/checkout@v2
      - name: restore lint result
        uses: actions/cache@v2
        with:
          path: ./**/build/reports/lint-results-*.xml
          key: ${{ runner.os }}-result-${{ github.sha }}-lint
      - name: restore ktlint result
        uses: actions/cache@v2
        with:
          path: ./**/build/reports/ktlint
          key: ${{ runner.os }}-result-${{ github.sha }}-ktlint
      - name: restore unit test result
        uses: actions/cache@v2
        with:
          path: ./**/build/test-results
          key: ${{ runner.os }}-result-${{ github.sha }}-unittest
      - name: setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: install yarn
        run: npm install -g yarn
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
